
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.semantic_release]
version_source = "file"
version_file = "Version"
upload_to_pypi = false
upload_to_release = false